module:
  imports:
    - path: github.com/LiquidPL/hugo-theme

baseURL: https://liquid.pw/
title: Chris Gutkowski
theme: github.com/LiquidPL/hugo-theme

sectionPagesMenu: main

defaultContentLanguage: en

languages:
  en:
    title: Chris Gutkowski
    weight: 1
  pl:
    title: Krzysztof Gutkowski
    weight: 2

params:
  links:
    - id: github
      name: GitHub
      icon: fab github
      url: https://github.com/LiquidPL
    - id: discord
      name: Discord
      icon: fab discord
      url: '#'
      tooltip: LiquidPL#1087
    - id: gitlab
      name: GitLab
      icon: fab gitlab
      url: https://gitlab.com/LiquidPL
    - id: twitter
      name: Twitter
      icon: fab twitter
      url: https://twitter.com/LiquidPL
